#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

killall dunst &

killall udiskie &


bspc monitor DP2-1 -d 1 2 3 4 5
bspc monitor DP2-2 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor VGA1 -d 1 2 3 4 5  
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP1 -d 1 2 3 4 5 6 7 8 9 10


bspc config pointer_follows_focus   true
bspc config split_ratio             0.5
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config border_radius           10
bspc config focused_border_color    \#fffacd
#bspc config active_border_color		\#ff79c6
#bspc config normal_border_color	    \#18100d
#bspc config presel_feedback_color	\#bf00f6
#bspc config focus_follows_pointer   true
bspc config border_width            1
bspc config window_gap              4
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config single_monocle			false
bspc config top_padding  25
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


#State configuration
bspc rule -a Uget-gtk state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Gthumb state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Guake state=floating
bspc rule -a Xarchiver state=pseudo_tiled
bspc rule -a Eog state=floating
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpick state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Gnome-calendar state=floating
bspc rule -a Galculator state=floating   
bspc rule -a Nitrogen state=floating
bspc rule -a xpad state=floating
bspc rule -a Orage state=floating

bspc config external_rules_command  ~/.config/bspwm/external_rules.sh

~/.config/polybar/launch.sh &

eww &

dunst &

uget-gtk &

uget-integrator-firefox &

uget-integrator &

megasync &

udiskie --smart-tray &

#greenclip daemon &

xidlehook --not-when-fullscreen --not-when-audio --timer normal 900 'betterlockscreen -l blur' '' &

xidlehook --timer normal 3600 'betterlockscreen -s blur' '' &

nm-applet &

sxhkd &

setxkbmap -option grp:alt_shift_toggle us,gr &


nitrogen --restore &

#autorandr docked &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1


xset -dpms s off
xfce4-power-manager 



#/home/harrkout/Documents/scripts/bspwm-dock/bspwm-dock

#xss-lock -l ~/Documents/scripts/transfer-sleep-lock-generic-delay.sh &

wmname LG3D


/home/harrkout/.config/polybar/scripts/autoname_workspaces.py

# rfkill block bluetooth

picom &


#feh --bg-scale /home/harrkout/Pictures/papes/plant2.jpg &


    bspc rule -a Pycalendar.py state=floating rectangle=600x400+986+27

sudo thinkfan -n

#wal -i /home/harrkout/Pictures/papes/van.jpg -n &

modprobe -r psmouse
modprobe psmouse

xrdb -merge ~/.Xresources &                                                       
xsetroot -cursor_name left_ptr &


#sleep when lid closes
xss-lock -l ~/Documents/scripts/transfer-sleep-lock-generic-delay.sh &

birdtray &

xrandr --output DP2-1 --set "Broadcast RGB" "Full"
xrandr --output DP2-2 --set "Broadcast RGB" "Full"
xrandr --output eDP1  --set "Broadcast RGB" "Full"
